"""add ip address

Revision ID: add_ip_address
Revises: 6a9f914f656c
Create Date: 2025-05-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_ip_address'
down_revision = '6a9f914f656c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=255), nullable=True))
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('ip_address')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('ip_address')
    # ### end Alembic commands ### 